Repository vuemontreal/vuemontreal, pull requests merged in 2020-03, with the labels that each got.

#75 left navbar
  assets/flag-fr.png
  assets/flag-us.png
  components/navbar/navbar-left.vue
Labels: feature, website-next

#74 Feat/top navbar(#61)
  components/navbar/navbar-top.vue
  layouts/default.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/events/_eventId.vue
  pages/index.vue
Labels: feature, website-next

#78 homepage events styles
  components/navbar/navbar-left.vue
  pages/index.vue
Labels: feature, website-next

#80 fix description for event in events
  pages/events/_eventDescription.vue
  pages/index.vue
Labels: bug, website-next

#81 Carousel
  components/carousel.vue
  components/eventDescription.vue
  layouts/default.vue
  package-lock.json
  package.json
  pages/index.vue
Labels: feature, website

#96 add skeleton
  .vscode/settings.json
  README.md
  layouts/default.vue
  package-lock.json
  package.json
  pages/index.vue
Labels: feature, vuemontreal 2.0

#99 update worfklow actions and update contributors
  .github/workflows/contributors.yml
  .github/workflows/nodejs.yml
  README.md
Labels: feature, vuemontreal 2.0

#98 add analytics
  nuxt.config.js
  package-lock.json
  package.json
Labels: feature, vuemontreal 2.0

#97 add storyblok + add fetch + generate + sb
  layouts/default.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/events/_eventId.vue
  pages/index.vue
Labels: feature, vuemontreal 2.0

#103 event page data display
  pages/events/_eventId.vue
Labels: feature, vuemontreal 2.0

#102 Mobile navigation
  components/navbar/navbar-left.vue
  components/navbar/navbar-top.vue
  layouts/default.vue
  package-lock.json
  store/index.js
Labels: feature, vuemontreal 2.0

#107 B/nav full width
  components/navbar/navbar-left.vue
  components/navbar/navbar-top.vue
  layouts/default.vue
  pages/events/_eventId.vue
  pages/index.vue
Labels: bug, website

#115 Feat/search design
  components/carousel.vue
  components/eventPreview.vue
  components/eventPreviewSkeleton.vue
  components/navbar/navbar-left.vue
  configs/buildModules.js
  configs/generate.js
  configs/i18n.js
  configs/modules.js
  configs/server.js
  layouts/error.vue
  nuxt.config.js
  pages/events/_eventId.vue
  pages/index.vue
  pages/search.vue
  store/index.js
Labels: feature, vuemontreal 2.0

#114 refacto nuxt config + add translation + correct carousel + modif navbar
  components/navbar/navbar-left.vue
Labels: bug, vuemontreal 2.0
