Repository vuemontreal/vuemontreal, pull requests merged in 2020-05, with the labels that each got.

#150 chore: clean up eslint rules
  .eslintrc.js
  .prettierrc
  components/navbar/navbar-top.vue
  configs/buildModules.js
  configs/generate.js
  configs/i18n.js
  configs/modules.js
  configs/server.js
  nuxt.config.js
  pages/events/_eventId.vue
  pages/search.vue
Labels: feature

#158 WIP storybook: adding storybook + chromatic
  .github/workflows/chromatic.yml
  .github/workflows/eslint.yml
  .storybook/main.js
  .storybook/preview.js
  README.md
  components/test.stories.js
  components/test.vue
  package-lock.json
  package.json
Labels: feature, vuemontreal 2.1

#161 design: implementing tokens and elements from figma
  .eslintrc.js
  .github/workflows/eslint.yml
  .storybook/main.js
  .storybook/preview-head.html
  .storybook/preview.js
  .vscode/settings.json
  assets/css/global.css
  components/elements/button.stories.js
  components/elements/button.vue
  components/elements/cards/cardevent.stories.js
  components/elements/cards/cardevent.vue
  components/elements/cards/cardjob.stories.js
  components/elements/cards/cardjob.vue
  components/elements/inputs/text-input.stories.js
  components/elements/inputs/text-input.vue
  components/elements/sponsor.stories.js
  components/elements/sponsor.vue
  components/index.js
  components/test.stories.js
  components/test.vue
  components/tokens/colors.stories.js
  components/tokens/icons/calendar-sharp.vue
  components/tokens/icons/chevron-back.vue
  components/tokens/icons/chevron-forward.vue
  components/tokens/icons/close-sharp.vue
  components/tokens/icons/icons.stories.js
  components/tokens/icons/logo-github.vue
  components/tokens/icons/logo-linkedin.vue
  components/tokens/icons/logo-youtube.vue
  components/tokens/icons/menu-outline.vue
  components/tokens/icons/notifications.vue
  components/tokens/icons/time-outline.vue
  components/tokens/texts/h1.vue
  components/tokens/texts/h2.vue
  components/tokens/texts/h3.vue
  components/tokens/texts/h4.vue
  components/tokens/texts/paragraph.vue
  components/tokens/texts/text.stories.js
  components/tokens/texts/textbutton.vue
  components/tokens/texts/textinfo.vue
  components/tokens/texts/textsmall.vue
  configs/head.js
  package-lock.json
  package.json
  tailwind.config.js
Labels: feature, vuemontreal 2.1

#165 doc: adding documentation to know how to work on the project
  README.md
  components/elements/button.vue
  components/elements/cards/cardevent.stories.js
  components/elements/cards/cardevent.vue
  components/elements/cards/cardjob.stories.js
  components/elements/cards/cardjob.vue
  components/elements/inputs/text-input.vue
  components/elements/sponsor.vue
  components/tokens/colors.stories.js
  components/tokens/icons/icons.stories.js
  docs/architecture.md
  docs/environment.md
  docs/styleguide.md
  docs/workflow.md
  package.json
  presentation.md
  tailwind.config.js
Labels: feature, vuemontreal 2.1

#184 F/#170 move cards to container
  components/index.js
  components/patterns/cards/cardevent.stories.js
  components/patterns/cards/cardevent.vue
  components/patterns/cards/cardjob.stories.js
  components/patterns/cards/cardjob.vue
Labels: feature, vuemontreal 2.1

#183 chore: adding stylelint with basic config and correct errors
  .github/workflows/lint.yml
  .stylelintrc.json
  components/elements/button.vue
  components/event-preview/event-preview-skeleton.vue
  components/event/event-skeleton.vue
  components/footer.vue
  components/navbar/navbar-top.vue
  components/patterns/cards/cardevent.vue
  components/patterns/cards/cardjob.vue
  configs/buildModules.js
  layouts/default.vue
  package-lock.json
  package.json
  pages/search.vue
  tailwind.config.js
Labels: feature, vuemontreal 2.1

#187 chore: update cards naming to match others and create speaker card
  components/index.js
  components/patterns/cards/card-event.stories.js
  components/patterns/cards/card-event.vue
  components/patterns/cards/card-job.stories.js
  components/patterns/cards/card-job.vue
  components/patterns/cards/card-speaker.stories.js
  components/patterns/cards/card-speaker.vue
  components/tokens/icons/document-outline.vue
Labels: feature, vuemontreal 2.1

#186 fix: add back mobile nav left white background
  layouts/default.vue
Labels: bug, vuemontreal 2.0

#188 F/#166 add header sidebar mobile
  .github/workflows/chromatic.yml
  .github/workflows/lint.yml
  .storybook/preview.js
  components/index.js
  components/navbar/navbar-left.vue
  components/patterns/navs/nav-mobile.stories.js
  components/patterns/navs/nav-mobile.vue
  components/patterns/navs/sidebar-mobile.vue
  components/tokens/icons/notifications-active.vue
  components/tokens/texts/textinfo.vue
  configs/head.js
  configs/i18n.js
  layouts/default.vue
  package-lock.json
Labels: feature, vuemontreal 2.1
